### ISSUE TITLE
Plugin Support for OpenSearch

### ISSUE THREAD

**Issue by soosinha** [chokolet/elasticsearch-analysis-seunjeon#2]
AWS has released OpenSearch with ALv2 license: https://github.com/opensearch-project/OpenSearch
Is there any plan to support this analyzer for OpenSearch ?

**Comment by chokolet** [comment]
I hasn't made any definite plans yet. but, this plugin is very similar 'nori-analyzer'. use that!
-> https://github.com/opensearch-project/OpenSearch/tree/main/plugins/analysis-nori
